
class Solution {
    public int romanToInt(String s) {
Scannerteclado = new Scanner (Sytem.in);

			int numero. i ;

			in vaNum []= (1000,900, 500, 400, 100, 90, 50, 40 10,9,5,4,1): String vaRom []=

			("M","CM" ,"D"", "CD", "C" ,"XC" ,"L", "XL", IX ,"V" , "I')


			While (true)

			{
				numero = teclado.het.Int ();


			  if (numero==0) 

			  break

			System.out.printf ("%-4d, numero);

			{

			if (numero 0>- vaNum [i] )

			{
				System.out.printf(vaRom[i]);


				numero = numero-vaNum [i];
			}

			else

			i++;
			}
			System.out.printf();
		}
	}
}


