class Solution {
    public int reverse(int x) {
      int[] arrayl = new int[] (1,2,3,4,5). System.out.println("array original:");
		for (int i-0:1 <arrayl.length ;i++)
  }

		System.butprint (arrayl [i]+ "");

		System.out.println();

		System.out.println("array final");

		 for (int 1 = arrayl.length-1; i>0;i--);
		 {
		 	System.out.println(array) [i]
		 	+"";

		 }
			
			int res = 0; While (x>0) {

ind = x % res=(re*10) + dig; x=x/10);

return res;
    }
}